language: python
python:
- '3.6'
- '3.7'
- '3.8'
services:
- docker
install:
- pip install -r requirements.txt
script:
- pycodestyle fdbk_mongodb_plugin
- pylint -E --enable=invalid-name,unused-import,useless-object-inheritance fdbk_mongodb_plugin
- docker run -dp 27017:27017 --name=mongo mongo:4-bionic
- coverage run --branch --source fdbk_mongodb_plugin/ -m unittest discover -s tst/
- coverage report -m
- docker rm -f mongo
deploy:
  provider: pypi
  user: __token__
  password:
    secure: hSbB/Gg5ltOk1h7bg0Na25OyO3RSRKPBTPflXWgsuVfmhuGtLwBTU3lV5o3Y6hABhZYXR95KBEXqdPwROdbNduOY8LnvtxvK8HIEC7RnMeyo+8KY5RbnFhxSENPNbFbv5KtPM07n+R6ScTVUqUhxHfWopsO6XdbE2Auim/04FC7RHU5rrRJi9elYOTCSO49iNBz2Eaw6gYpO/FW1XCftGE75Z4VQ/InlxvKLxgnMrtdu+P33qj4q7LrpJjFb/pAmBKGOnyOc6dA2OniIjFV3hCE1ggfU1ho6lvP59jNp2h69jP2cnQqbgdOwFBB4C2eyNYz91cnngKoiIklp8OccfQYm6/3URzmgW+yXniXykd0slJbHSceBxivAElxlc8kXEPKVQFw8zmh6si9vseCWmZGdkrexZBzydiBrihZ16VVmLsGxi8AY6FxMb0uzAWoGyxB0yia209M1RuRW1EfaIrk1oQusI2wMkCW2NMLlNs64N6De0+zUlChxXt5K+PIT2U7xIuNk3l4k+JdApTOUBtv1hUb3PZTGFrw7fT7MlpcUkaYyFvp3Mp9tof5dTVSeDZ6YlhxmVYVJ89Qmk/ERsK76QzQygnoYkivWYLO9My6nv8hpivan5zk6fPhqpAEmxpYcp3pfqj9AM7zc9pv1Sz1D4pAHVEhxszYDS5XpnLM=
  on:
    tags: true
    python: 3.7
